name: Build Unity project
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Unity
        uses: actions/setup-unity@v1
        with:
          version: '2020.1.17f1'
          architecture: 'x86_64'
      - name: Build Unity project
        run: /opt/Unity/Editor/Unity -batchmode -nographics -projectPath $(pwd) -buildLinuxUniversalPlayer "$(pwd)/Build/linux.build" -quit
